source 'http://rubygems.org'

gem 'rails', '3.1.3'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2'

gem 'rails-i18n'

gem 'authlogic'
gem 'cancan'

gem 'rake', '0.9.2.2'
gem 'therubyracer'
gem 'execjs'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

# for kosapi
gem 'yard'
gem 'yajl-ruby'
gem 'rest-client'
gem 'rest-client-components'

gem 'jquery-rails'

gem 'simple_form', :git => 'git://github.com/plataformatec/simple_form.git'
gem 'twitter-bootstrap-rails'

gem "paperclip"
gem "ckeditor", "3.7.0.rc2"

gem 'will_paginate', '~> 3.0.pre4'



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '0.8.2', :require => false
end
